
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="/bootstrap.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" type="image/ico" href="/rumenz.ico" />

    <link rel="stylesheet" href="/use.css?v=1.0">
    <#--<meta name="baidu-site-verification" content="RNO4eFU9Xq" />-->
    <#--<meta name="360-site-verification" content="975cb8ba2637a75b427e9cd54d2e2d72" />-->
    <meta name="keywords" content="入门学习,学习的小站点">
    <meta name="description" content="WIKI教程：入门编程学习的小站点">
    <title> ${title}WIKI教程</title>
</head>
<body>
<div class="container">
    <h1 class="use-logo">
        <a href="/" >WIKI教程</a>
    </h1>
</div>