<ul class="list-group">
    <li  class="list-group-item d-flex">
        <a href="/coding/">编程技术</a>
    </li>
    <li  class="list-group-item d-flex">
        <a href="/java_tech/">JAVA技术</a>
    </li>
    <li  class="list-group-item d-flex">
        <a href="/python_coding/">PYTHON编程</a>
    </li>
    <li  class="list-group-item d-flex">
        <a href="/webcoding/">WEB开发</a>
    </li>
    <li  class="list-group-item d-flex">
        <a href="/script/">脚本语言</a>
    </li>
</ul>