<ul class="list-group">
    <li  class="list-group-item d-flex">
        <a href="/zhuanlan/">极客专栏</a>
    </li>
    <li  class="list-group-item d-flex">
        <a href="/video/">极客视频</a>
    </li>
    <li  class="list-group-item d-flex">
        <a href="/python_coding/">PYTHON编程</a>
    </li>
    <li  class="list-group-item d-flex">
        <a href="/webcoding/">WEB开发</a>
    </li>
    <li  class="list-group-item d-flex">
        <a href="/script/">脚本语言</a>
    </li>
</ul>